name: Deploy App to GKE

on:
  push:
    branches:
    - 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    - name: code checkout
      uses: actions/checkout@v2

    - name: install the gcloud cli
      uses: google-github-actions/setup-gcloud@v0
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        install_components: 'gke-gcloud-auth-plugin'
        export_default_credentials: true

    - name: build and push the docker image
      env:
        GOOGLE_PROJECT: ${{ secrets.GCP_PROJECT_ID }}
      run: |
        gcloud auth configure-docker us-central1-docker.pkg.dev
        docker build -t us-central1-docker.pkg.dev/$GOOGLE_PROJECT/portfolio-repo/portfolio:latest .
        docker push us-central1-docker.pkg.dev/$GOOGLE_PROJECT/portfolio-repo/portfolio:latest

    - name: rollout the changes
      run: |
        gcloud container clusters get-credentials red-studios --zone us-central1 --project ${{ secrets.GCP_PROJECT_ID }}
        kubectl rollout restart deployment portfolio-gke